"""
Django settings for easyrent_demo project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os # Asegúrate de que os esté importado al principio
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z#&u^j!lq!#t6^l7d0794s4%v3t7z#q167z*!s)o&5#i%14^m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Mantén en True para desarrollo, cambia a False para producción

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'propiedades', # Tu aplicación 'propiedades'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'easyrent_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Aquí se indica a Django dónde buscar plantillas a nivel de proyecto
        # Si tienes una carpeta 'templates' en la raíz del proyecto, asegúrate de que esté aquí.
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Puedes añadir 'templates' aquí si tienes plantillas globales
        'APP_DIRS': True, # MUY IMPORTANTE: Esto le dice a Django que busque plantillas dentro de los directorios 'templates' de cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': { # MUY IMPORTANTE: Registra tus custom tags aquí
                'custom_tags': 'propiedades.templatetags.custom_tags',
            }
        },
    },
]

WSGI_APPLICATION = 'easyrent_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-mx' # O 'es-es', según tu preferencia

TIME_ZONE = 'America/Guayaquil' # Ajusta a tu zona horaria local

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Este es el directorio global donde puedes colocar archivos estáticos
# directamente en la raíz de tu proyecto (ej. easyrent_demo/static/).
# Si ya tienes la carpeta 'static' en la raíz, esta línea es correcta.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Directorio donde `collectstatic` recolectará todos los archivos estáticos
# para su despliegue en producción.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_collected')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para archivos de usuario (subidos por Media)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URLs de redirección para autenticación
LOGIN_REDIRECT_URL = 'user_dashboard' # Redirige al dashboard después del login exitoso
LOGOUT_REDIRECT_URL = 'welcome_page' # Redirige a la página de bienvenida después del logout
LOGIN_URL = 'login' # La URL para la vista de login (usada por @login_required)