# Generated by Django 5.0.4 on 2025-05-23 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_banios_propiedad_ciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='propietario',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='banios',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(default='Ciudad Desconocida', max_length=100),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='habitaciones',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='pais',
            field=models.CharField(default='País Desconocido', max_length=100),
        ),
    ]
