# Generated by Django 5.0.4 on 2025-05-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_remove_propiedad_propietario_propiedad_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades_pics/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.IntegerField(default=0),
        ),
    ]
