# Generated by Django 5.2.1 on 2025-05-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_propiedad_latitud_propiedad_longitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='longitud',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
