# Generated by Django 5.0.4 on 2025-05-23 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_remove_propiedad_latitud_remove_propiedad_longitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='banios',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='habitaciones',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='pais',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='num_banos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='num_habitaciones',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades_imagenes/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
