# Generated by Django 5.2.1 on 2025-05-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_propiedad_pais_propiedad_tipo_propiedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='caracteristicas_adicionales',
            field=models.TextField(blank=True, help_text="Ej: 'Piscina, Jardín, Vista al mar'", null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tiene_garaje',
            field=models.BooleanField(default=False),
        ),
    ]
