# Generated by Django 5.2.1 on 2025-06-01 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0009_propiedad_caracteristicas_adicionales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='caracteristicas_adicionales',
            field=models.TextField(blank=True, help_text='Ej: Piscina, Jardín, Balcón, Seguridad 24/7', null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='num_banos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='num_habitaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('local_comercial', 'Local Comercial'), ('oficina', 'Oficina'), ('bodega', 'Bodega')], default='casa', max_length=50),
        ),
    ]
