# Generated by Django 5.2.1 on 2025-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='pais',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='caracteristicas_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('oficina', 'Oficina'), ('local_comercial', 'Local Comercial')], default='casa', max_length=50),
        ),
    ]
