# Generated by Django 5.2.1 on 2025-06-01 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0012_remove_propiedad_pais_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='pais',
            field=models.CharField(default='Ecuador', max_length=100),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='caracteristicas_adicionales',
            field=models.TextField(blank=True, help_text='Ej: Piscina, Jardín, Balcón, Seguridad 24/7', null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('local_comercial', 'Local Comercial'), ('oficina', 'Oficina'), ('bodega', 'Bodega')], default='casa', max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
