# Generated by Django 5.2.1 on 2025-06-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0014_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='imagen',
            new_name='imagen_principal',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='caracteristicas_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='num_banos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='num_habitaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('terreno', 'Terreno'), ('oficina', 'Oficina'), ('local_comercial', 'Local Comercial'), ('bodega', 'Bodega'), ('villa', 'Villa'), ('condominio', 'Condominio'), ('duplex', 'Dúplex'), ('penthouse', 'Penthouses')], default='casa', max_length=50),
        ),
    ]
