# Generated by Django 5.2.1 on 2025-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0017_imagenpropiedad_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='propiedad',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='respuesta_a',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ia_calificacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificación IA'),
        ),
        migrations.DeleteModel(
            name='ImagenPropiedad',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
